# Generated by Django 3.0.5 on 2022-04-16 19:56

from django.db import migrations, models
import djongo.models.fields
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('categories', djongo.models.fields.JSONField()),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_of_occurrence', models.DateTimeField()),
                ('location', djongo.models.fields.EmbeddedField(model_container=events.models.Address)),
                ('ratings', djongo.models.fields.ArrayField(default=[], model_container=events.models.Rating)),
            ],
        ),
    ]
